### PR TITLE
[ru] Add translations

### PR DESCRIPTION
**Pull request by NikitaIT**

### CODE REVIEW

**Comment by greggman** [comment]
sorry, I didn't realize I broke the link system. am fixing now. Links should stay same as English

**Comment by NikitaIT** [comment]
I replaced "resurses/" to "../resurses/" for all in [ru]

**Comment by NikitaIT** [comment]
@greggman in threejs-multiple-scenes exemple not shown
`{{{examples url="../threejs-multiple-scenes-controls.html" }}}`

**Comment by greggman** [comment]
Thanks. I fixed a bunch of links and pushed a new build script to check some of them in the future

**Comment by NikitaIT** [comment]
now i corrected the links in PR

**Comment by NikitaIT** [comment]
I stopped to understand what was going on and got

```
...
processing:  threejs\lessons\index.md
Wrote: out\threejs\lessons\index.html
Processing Lang: ru
processing:  threejs/lessons/ru/threejs-cameras.md
Fatal error: URL is not defined
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! threejsfundamentals@0.0.1 build: `grunt`
npm ERR! Exit status 3
```

**Comment by greggman** [comment]
Sorry, you need node 11 (not sure which version of node added `URL`

**Pull request merged**
